# Pytorch Tensor Funtions
##### *Created by Naman Singhal*
 Get to know me better with [my Linkedin](https://www.linkedin.com/in/namansnghl/)
 <hr>

## An Introduction to Pytorch

PyTorch is an open source machine learning library based on the Torch library,used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab.<br> Pytorch contains a datatype called as 'Tensor'(torch.Tensor) which is a special array. A Tensor is capable of storing both a scalar value and a multidimentional matrix with same data-type. A Tensor can be created from python Data types and can be converted back. In addition these tensors can be used to perform special inbuild functions and mathematical operation.
Note: A Tensor is capable of storing matrices beyond 3D


### Creating a tensor with pre-defined data

In [6]:
#2 dimensional tensor
new_tensor = torch.tensor([[2. ,3.],[4. ,5.],[6.,1.]])
print(new_tensor)

tensor([[2., 3.],
        [4., 5.],
        [6., 1.]])


###### Few funtions which will be discussed in this notebook:
- [torch.reshape()](#1)
- [torch.tensor.apply_()](#2)
- [torch.matmul()](#3)
- [torch.unique()](#4)
- [torch.stack()](#5)

In [2]:
# Import torch and other required modules
import torch

In [2]:
%config Completer.use_jedi = False

## <a id='1'></a>Function 1 - torch.reshape(input, shape) → Tensor

This function is used to change the dimension(shape/size) of a tensor(matrix). The function returns new tensor and does not modify tensor inplace.

In [3]:
# Example 1 - working (change this)
tensor = torch.tensor([1,2,3,4,5,1,24,4,5,6,7,8])
tensor2 = torch.reshape(tensor,(4,3))
print('Dimension - ',tensor.size())
print('New Dimension - ',tensor2.size())

Dimension -  torch.Size([12])
New Dimension -  torch.Size([4, 3])


In [4]:
#printing the number of elements
tensor.numel()

12

A tensor of 12 elements can be reshaped to any dimension `(n x p x l x ...)` such that the elements perfectly fit in the new shape with no extra space or less space

In [5]:
# Example 2
tensor = torch.tensor([2,1,2,3,4,5,1,24,4,5,6,7,8,2,5,6,8,9]).reshape(3,6)
tensor2 = torch.reshape(tensor,(3,3,2))
print('{}\nDimension - '.format(tensor),tensor.shape)
print('\n{}\nNew Dimension - '.format(tensor2),tensor2.size())

tensor([[ 2,  1,  2,  3,  4,  5],
        [ 1, 24,  4,  5,  6,  7],
        [ 8,  2,  5,  6,  8,  9]])
Dimension -  torch.Size([3, 6])

tensor([[[ 2,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 1, 24],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  2],
         [ 5,  6],
         [ 8,  9]]])
New Dimension -  torch.Size([3, 3, 2])


`mat(3 * 6)` has `18` elements. After reshaping `mat(3 * 3 * 2)` has 18 elements. Hence no space is extra or less in new matrix

In [6]:
# Example 3 - breaking (to illustrate when it breaks)
tensor = torch.tensor([2,1,2,3,4,5,1,24,4,5,6,7,8,2,5,6,8,9]).reshape(3,6)
print('{}\nDimension - '.format(tensor),tensor.shape)
tensor2 = torch.reshape(tensor,(3,3,3))
print('\n{}\nNew Dimension - '.format(tensor2),tensor2.size())

tensor([[ 2,  1,  2,  3,  4,  5],
        [ 1, 24,  4,  5,  6,  7],
        [ 8,  2,  5,  6,  8,  9]])
Dimension -  torch.Size([3, 6])


RuntimeError: shape '[3, 3, 3]' is invalid for input of size 18

The code breaks when reshaped matrix has more or less space for elemets. Here `18` elements were tried to fit in a matrix with dimesions `[3,3,3]` which can hold upto `27` elements(creates extra null space for `9` elements)<hr>

## Function 2 - tensor.apply_(callable)<a id='2'></a>

The `.apply_()` function of Pytorch is similar to the `.apply()` function from pandas. This function is used to perform an operation over all the elements of a tensor. It takes an argument as a callble funtion/lambda function which alters and returns modified values of tensor. `.apply_()` is an inplace function

Let us now declare a 2D Tensor with float data type

In [7]:
#Example - 1
tensor = torch.tensor([[3,5,1,2],[3,1,5,3],[7,5,8,3]],dtype=torch.float)
print(tensor)

tensor([[3., 5., 1., 2.],
        [3., 1., 5., 3.],
        [7., 5., 8., 3.]])


The objective is to increment the values of the tensor by '0.2'

In [8]:
tensor.apply_(lambda x: (x+0.2))
tensor

tensor([[3.2000, 5.2000, 1.2000, 2.2000],
        [3.2000, 1.2000, 5.2000, 3.2000],
        [7.2000, 5.2000, 8.2000, 3.2000]])

The `lambda` function declared return `x + 0.2` i.e. an incremented value of x by 0.2 where x is an element from tensor(matrix).
The lambda funtion is then performed of every element

In [9]:
# Example 2 - working
tensor2 = torch.tensor([[3,5,1,2],[3,1,5,3],[7,5,8,3]])
print('Original Tensor:\n{}\n'.format(tensor2))

def check_three(x):
    if x==3:
        return 0
    else:
        return x

tensor2.apply_(check_three)
print('Modified Tensor:\n{}'.format(tensor2))

Original Tensor:
tensor([[3, 5, 1, 2],
        [3, 1, 5, 3],
        [7, 5, 8, 3]])

Modified Tensor:
tensor([[0, 5, 1, 2],
        [0, 1, 5, 0],
        [7, 5, 8, 0]])


In the above example we have created a function `check_three(x)` that simply checks the element `3` and replaces it with `0`.<br>the `.apply_()` takes the funtion and passes elements from the matrix `tensor2` one by one. The funtion returns `0` if the elemnt is `3` else returns the element itself

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
tensor2 = torch.tensor([[3,5,1,2],[3,1,5,3],[7,5,8,3]])
print('Original Tensor:\n{}\n'.format(tensor2))

def find_three(x):
    if x==3:
        print('Found 3')
    else:
        return x

tensor2.apply_(find_three)
print('Modified Tensor:\n{}'.format(tensor2))

Original Tensor:
tensor([[3, 5, 1, 2],
        [3, 1, 5, 3],
        [7, 5, 8, 3]])

Found 3


TypeError: an integer is required (got type NoneType)

In the above example I modified `check_three()` to `find_three()` function to demonstrate how `.apply_()` breaks.<br>
`find_three()` prints `'Found 3'` if 3 is found and does not return anything. In this case the code breaks as the `.apply_()` method expects a return value for every value it passes in a function (`callable`). `.apply_()` is used to modify values in tensor and if no value is returned it throws error.

`.apply_()` is a very handy function when playing with data but must be used with caution.<hr>

## Function 3 - torch.matmul(input, other, out=None) → Tensor<a id='3'></a>

`.matmul()` is a matrix multiplication function for two tensors.<br><br>

The behavior depends on the dimensionality of the tensors as follows:
- If both tensors are 1-dimensional, the dot product (scalar) is returned.
- If both arguments are 2-dimensional, the matrix-matrix product is returned.
- If the first argument is 1-dimensional and the second argument is 2-dimensional, a 1 is prepended[(broadcasted)](https://www.youtube.com/watch?v=DEqIiH_bkFc) to its dimension for the purpose of the matrix multiply . After the matrix multiply, the prepended dimension is removed.
- If the first argument is 2-dimensional and the second argument is 1-dimensional, the matrix-vector product is returned.
- If one argument is >=1D and other is >=2D then a batch matrix multiplication is performed where the lower dimension matrix is brought to a dimension equal to the other matrix byprepending a 1 in dimention. Later the prepended dimension is removed.
<br><br>*Example:*<br>
Assume the dimensions of 2 matrix as - `[j, 1, n, p]` @ `[k, n, p]`<br>
The lower dim `[k, n, p]` is brought to higher dimension by prepending dim(1) -  `[j, 1, n, p]` * `[1, k, n, p]` (broadcasting step)<br>
Result:`[j, k, n, p]`<br>
*Note: the above matric multiplication is valid as the number of columns `p` in `mat[j, 1, n, p]` is equal to number of rows `p` in `mat[k, n, p]`*<br>*(Recommended reading [Matrix Multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html))*<br><br>
*Bonus Note: `@` is a left associated operator introduced to substitute .matmul() funtion and make matrix multiplication easier to read and perform*

In [11]:
#example 1
mat1 = torch.tensor([1,2,1])
mat2 = torch.tensor([[3,2],[5,2],[6,1]])

print('matrix 1:\n{}\n\nmatrix 2:\n{}\n'.format(mat1,mat2))
print('Matrix Multiplication Result:\n{}'.format(torch.matmul(mat1,mat2)))

matrix 1:
tensor([1, 2, 1])

matrix 2:
tensor([[3, 2],
        [5, 2],
        [6, 1]])

Matrix Multiplication Result:
tensor([19,  7])


Explanation:
```
              [3, 2]
[1, 2, 1] *   [5, 2]     =   [1*3 + 2*5 + 6*1, 1*2 + 2*2 + 1*1]     =     [19,7]
              [6, 1]
```        

In [12]:
# Example 2
t1 = torch.tensor([x for x in range(1,25)]).reshape([2,3,4])
t2 = torch.tensor([x for x in range(1,21)]).reshape([4,5])
print('matrix 1:\n{}\n\nmatrix 2:\n{}\n'.format(t1,t2))
multiplied_with_matmul = torch.matmul(t1,t2)
print('Matrix Multiplication Result:\n{}'.format(multiplied_with_matmul))

matrix 1:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

matrix 2:
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

Matrix Multiplication Result:
tensor([[[ 110,  120,  130,  140,  150],
         [ 246,  272,  298,  324,  350],
         [ 382,  424,  466,  508,  550]],

        [[ 518,  576,  634,  692,  750],
         [ 654,  728,  802,  876,  950],
         [ 790,  880,  970, 1060, 1150]]])


In [13]:
print('''Martix t1 shape = {}
Martix t2 shape = {}
Martix Multiplication result shape = {}'''.format(t1.shape,t2.shape,multiplied_with_matmul.shape))

Martix t1 shape = torch.Size([2, 3, 4])
Martix t2 shape = torch.Size([4, 5])
Martix Multiplication result shape = torch.Size([2, 3, 5])


In the above matrix multiplication `mat[2,3,4]` @ `mat[4,5]`, number of columns `4` is equal to number of rows `4` but the dimensions are not same.<br>
`mat[2,3,4]` @ `mat[4,5]`<br>
`mat[2,3,4]` @ `mat[1,4,5]`(broadcasting step)<br>
Resultant - `mat[2,3,5]`

In [14]:
#BONUS
multiplied_with_operator = t1 @ t2
multiplied_with_matmul == multiplied_with_operator

tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])

Hence `@` is same as matmul()

Explanation about example

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
t1 = torch.tensor([x for x in range(1,25)]).reshape([3,4])
t2 = torch.tensor([x for x in range(1,16)]).reshape([3,5])
t1 @ t2

RuntimeError: shape '[3, 4]' is invalid for input of size 24

If the number of columns of 1st tensor is not same as the number of rows of 2nd tensor then multiplication cannot be performed.<hr>

## Function 4 - torch.unique(input, sorted=True, return_inverse=False, dim=None)<a id='4'></a>

Returns the unique elements of the input tensor.

> Parameters
- input (Tensor) – the input tensor
- sorted (bool) – Whether to sort the unique elements output.
- return_inverse (bool) – Whether to also return the indices for where elements in the original input ended up in the returned unique list.
- return_counts (bool) – Whether to also return the counts for each unique element.
- dim (int) – the dimension to apply unique. If None, the unique of the flattened input is returned. default: None

In [16]:
# Example 1 - working
torch.unique(torch.tensor([1, 3, 2, 3], dtype=torch.float))

tensor([1., 2., 3.])

the tensor `[1,3,2,3]` was converted to mentioned data-type i.e. `float` and unique values were returned

In [18]:
# Example 2 - working
tensor = torch.tensor([[9, 1, 3, 2, 3],[3,5,1,7,1]])
UniqueNew, loc = torch.unique(tensor, return_inverse=True)
print(UniqueNew,loc,sep='\n\n')

tensor([1, 2, 3, 5, 7, 9])

tensor([[5, 0, 2, 1, 2],
        [2, 3, 0, 4, 0]])


The `return_inverse=True` returned a tensor `loc` that stores indices of the elements of new tensor from the old tensor.<br>
`loc[0][0]=5` meaning `tensor[0][0]` is stored as `UniqueNew[5]`<hr>

## Function 5 - torch.stack(tensors, dim=0, out=None) → Tensor<a id='5'></a>

Concatenates sequence of tensors along a new dimension.
>Parameters
- tensors – sequence of tensors to concatenate
- dim (int)(AKA axis) – dimension to insert. Has to be between 0 and the number of dimensions of concatenated tensors (inclusive)
- out (Tensor, optional) – the output tensor.

Note - All tensors need to be of the same in same dimension. Stacking is not same as concatenating as stacking means adding over another tensor in new dimension and concatenating is adding in given dimensions<br>
So if `A` and `B` are of shape `(3, 4)`, `torch.cat([A, B], dim=0)` will be of shape `(6, 4)` and `torch.stack([A, B], dim=0)` will be of shape `(2, 3, 4)`.

In [19]:
# Example 1 - working
tensor1 = torch.tensor([x for x in range(1,7)]).reshape([2,3])
tensor2 = torch.tensor([x for x in range(7,13)]).reshape([2,3])
print('matrix 1:\n{}\n\nmatrix 2:\n{}\n'.format(tensor1,tensor2))
concat = torch.stack([tensor1,tensor2],dim=0)
print('matrix1 stacked matrix 2:\n{}'.format(concat))
print('Dimension\n{}'.format(concat.shape))

matrix 1:
tensor([[1, 2, 3],
        [4, 5, 6]])

matrix 2:
tensor([[ 7,  8,  9],
        [10, 11, 12]])

matrix1 stacked matrix 2:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Dimension
torch.Size([2, 2, 3])


In the above example the two matrices are stacked over each other in a new dimension. `[2,3]` stacked over `[2,3]` resulted in `[2,2,3]` i.e. two `[2,3]` stacked in 3D

In [20]:
# Example 2 - working
tensor1 = torch.tensor([x for x in range(1,13)]).reshape([2,2,3])
tensor2 = torch.tensor([x for x in range(1,13)]).reshape([2,2,3])
print('matrix 1:\n{}\n\nmatrix 2:\n{}\n'.format(tensor1,tensor2))
concat = torch.cat([tensor1,tensor2], dim=2)
print('matrix1 stacked matrix 2:\n{}'.format(concat))
print('Dimension\n{}'.format(concat.shape))

matrix 1:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

matrix 2:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

matrix1 stacked matrix 2:
tensor([[[ 1,  2,  3,  1,  2,  3],
         [ 4,  5,  6,  4,  5,  6]],

        [[ 7,  8,  9,  7,  8,  9],
         [10, 11, 12, 10, 11, 12]]])
Dimension
torch.Size([2, 2, 6])


We have stacked the two tensors along `dim = 2` meaning `[n x p x l]` along the `l` axis

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
tensor1 = torch.tensor([x for x in range(1,7)]).reshape([2,3])
tensor2 = torch.tensor([x for x in range(7,13)]).reshape([1,6])
print('matrix 1:\n{}\n\nmatrix 2:\n{}\n'.format(tensor1,tensor2))
concat = torch.stack([tensor1,tensor2],dim=0)
print('matrix1 stacked matrix 2:\n{}'.format(concat))
print('Dimension\n{}'.format(concat.shape))

matrix 1:
tensor([[1, 2, 3],
        [4, 5, 6]])

matrix 2:
tensor([[ 7,  8,  9, 10, 11, 12]])



RuntimeError: stack expects each tensor to be equal size, but got [2, 3] at entry 0 and [1, 6] at entry 1

In this example the code breaks easily as the two tensors have a different dimension. `[2,3]` cannot be stacked over a `[1,6]`

It is always better to use the `.cat()` if dimensions are not same<hr>

## Conclusion

This covers all the 5 PyTorch Tensor functions that are very useful when handling real data. To learn more about tensor functions in putorch refer the links in reference

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html